name: Build

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - published
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  MINVERBUILDMETADATA: build.${{ github.run_number }}

jobs:
  build:
    name: pipeline-${{ matrix.os }}-dotnet-${{ matrix.dotnet-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet-version: ['10.0.x']
        
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
        with:
          lfs: true
          fetch-depth: 0

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '${{ matrix.dotnet-version }}'

      - name: List Installed SDKs
        run: dotnet --list-sdks

      - name: Create temporary global.json
        run: echo '{"sdk":{"version":"${{ matrix.dotnet-version }}"}}' > global.json

      - name: Dotnet Tool Restore
        run: dotnet tool restore
        shell: pwsh

      - name: Dotnet Cake Build
        run: dotnet cake --target=Build
        shell: pwsh
        
      - name: Dotnet Cake Pack
        run: dotnet cake --target=Pack
        shell: pwsh

      - name: Upload NuGet packages
        uses: actions/upload-artifact@v7
        with:
          name: nuget-packages-${{ matrix.dotnet-version }}
          path: ./Artifacts/*.nupkg

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download NuGet packages for .NET 10.0
        uses: actions/download-artifact@v8
        with:
          name: nuget-packages-10.0.x
          path: ./Artifacts

      - name: Push to GitHub Packages
        run: dotnet nuget push ./Artifacts/*.nupkg --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
